2023-06-21 16:12:42,933	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:12:43,406	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:12:43,601	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:12:44,049	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:12:44,627	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:12:44,808	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:12:45,482	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:32:09,109	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:32:09,365	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:32:09,366	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:32:10,650	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:32:10,712	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:32:10,811	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:32:11,014	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:33:48,820	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:35:26,790	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:36:44,147	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:36:44,473	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:36:44,572	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:36:45,420	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:36:45,965	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 16:36:46,304	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 17:01:01,022	ERROR	Error 61 connecting to 52.35.64.124:6378. Connection refused.
2023-06-21 17:01:01,034	ERROR	Exception calling application: Cannot set cms.GetNextBatchForJobResponse.batch_data to False: False has type <class 'bool'>, but expected one of: (<class 'bytes'>, <class 'str'>) for field GetNextBatchForJobResponse.batch_data
Traceback (most recent call last):
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 702, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/type_checkers.py", line 211, in CheckValue
    raise TypeError(message)
TypeError: False has type <class 'bool'>, but expected one of: (<class 'bytes'>, <class 'str'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 558, in init
    setattr(self, field_name, field_value)
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 704, in field_setter
    raise TypeError(
TypeError: Cannot set cms.GetNextBatchForJobResponse.batch_data to False: False has type <class 'bool'>, but expected one of: (<class 'bytes'>, <class 'str'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/grpc/_server.py", line 494, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/Users/patrickwatters/Projects/super/sdl-server/server.py", line 122, in GetNextBatchForJob
    return pb2.GetNextBatchForJobResponse(**result)
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 560, in init
    _ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 477, in _ReraiseTypeErrorWithFieldName
    raise exc.with_traceback(sys.exc_info()[2])
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 558, in init
    setattr(self, field_name, field_value)
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 704, in field_setter
    raise TypeError(
TypeError: Cannot set cms.GetNextBatchForJobResponse.batch_data to False: False has type <class 'bool'>, but expected one of: (<class 'bytes'>, <class 'str'>) for field GetNextBatchForJobResponse.batch_data
2023-06-21 17:05:40,861	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 17:05:41,079	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 17:05:41,209	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 17:05:41,210	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 17:05:41,381	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 17:05:41,382	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 17:05:41,705	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 17:05:46,242	ERROR	client internal error
2023-06-21 17:05:46,262	ERROR	Exception calling application: Cannot set cms.GetNextBatchForJobResponse.batch_data to False: False has type <class 'bool'>, but expected one of: (<class 'bytes'>, <class 'str'>) for field GetNextBatchForJobResponse.batch_data
Traceback (most recent call last):
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 702, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/type_checkers.py", line 211, in CheckValue
    raise TypeError(message)
TypeError: False has type <class 'bool'>, but expected one of: (<class 'bytes'>, <class 'str'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 558, in init
    setattr(self, field_name, field_value)
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 704, in field_setter
    raise TypeError(
TypeError: Cannot set cms.GetNextBatchForJobResponse.batch_data to False: False has type <class 'bool'>, but expected one of: (<class 'bytes'>, <class 'str'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/grpc/_server.py", line 494, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/Users/patrickwatters/Projects/super/sdl-server/server.py", line 122, in GetNextBatchForJob
    return pb2.GetNextBatchForJobResponse(**result)
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 560, in init
    _ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 477, in _ReraiseTypeErrorWithFieldName
    raise exc.with_traceback(sys.exc_info()[2])
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 558, in init
    setattr(self, field_name, field_value)
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 704, in field_setter
    raise TypeError(
TypeError: Cannot set cms.GetNextBatchForJobResponse.batch_data to False: False has type <class 'bool'>, but expected one of: (<class 'bytes'>, <class 'str'>) for field GetNextBatchForJobResponse.batch_data
2023-06-21 17:05:49,766	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 17:05:49,982	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 17:05:50,219	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 17:11:12,135	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 17:11:12,502	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 17:11:12,778	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 17:11:13,282	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 17:11:13,504	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 17:11:14,209	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 17:11:15,011	WARNING	Connection pool is full, discarding connection: lambda.us-west-2.amazonaws.com. Connection pool size: 10
2023-06-21 19:01:03,363	ERROR	client internal error
2023-06-21 19:01:03,374	ERROR	Exception calling application: Cannot set cms.GetNextBatchForJobResponse.batch_data to False: False has type <class 'bool'>, but expected one of: (<class 'bytes'>, <class 'str'>) for field GetNextBatchForJobResponse.batch_data
Traceback (most recent call last):
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 702, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/type_checkers.py", line 211, in CheckValue
    raise TypeError(message)
TypeError: False has type <class 'bool'>, but expected one of: (<class 'bytes'>, <class 'str'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 558, in init
    setattr(self, field_name, field_value)
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 704, in field_setter
    raise TypeError(
TypeError: Cannot set cms.GetNextBatchForJobResponse.batch_data to False: False has type <class 'bool'>, but expected one of: (<class 'bytes'>, <class 'str'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/grpc/_server.py", line 494, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/Users/patrickwatters/Projects/super/sdl-server/server.py", line 122, in GetNextBatchForJob
    return pb2.GetNextBatchForJobResponse(**result)
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 560, in init
    _ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 477, in _ReraiseTypeErrorWithFieldName
    raise exc.with_traceback(sys.exc_info()[2])
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 558, in init
    setattr(self, field_name, field_value)
  File "/Users/patrickwatters/opt/anaconda3/envs/super/lib/python3.9/site-packages/google/protobuf/internal/python_message.py", line 704, in field_setter
    raise TypeError(
TypeError: Cannot set cms.GetNextBatchForJobResponse.batch_data to False: False has type <class 'bool'>, but expected one of: (<class 'bytes'>, <class 'str'>) for field GetNextBatchForJobResponse.batch_data
